### PR TITLE
Add webhook stores

### PR DESCRIPTION
**Pull request by rubenvanassche**
Add the possibility to implement your own WebhookStore: your own implementation of storing a WebhookCall model in the database.

### CODE REVIEW

**Comment by rubenvanassche** [comment]
Ideas for better name are welcome :)

**Comment by freekmurze** [comment]
The intent isn't clear to me. If you want to use another model or table, you can specify that in the config. My feeling is that have a store layer on top is too complex.

Maybe you could guide me through the actual use case where this is needed.

**Comment by rubenvanassche** [comment]
So in a project we're building right now we need some additional data on the model, though this data can also be found in the raw JSON payload, you don't want to use this field to query for certain webhooks(what if the format of the JSON changes through the application lifetime).  

For example in our project we have a status attached to each webhook, we need to check if a status was already received in the past so we can accept/reject the webhook coming in. So a simple `->where('status', $status)` is the best solution for this. 

The problem with the current implementation of the package is that we have no control over the creation of the webhook model. This means our status column should be null so an initial webhook model can be constructed without errors. But at time of creating the model we have the status field, so why not fill it right in? This is where this PR become important, you can create a model with a status column filled in by creating a custom webhook store class which handles the creating of the model.

**Comment by freekmurze** [comment]
How about creating your own model, and add a `created` callback on it. In that callback you could do whatever you want.

In the package we could to add a dedicated `storeWebhook` method on the the current `WebhookCall` model and use that instead of the `create` method. That way people can override that method as well.  The upside of this solution is that we don't need to introduce an extra concept like `store`.

**Comment by rubenvanassche** [comment]
> In the package we could to add a dedicated storeWebhook method on the the current WebhookCall model and use that instead of the create method. That way people can override that method as well. The upside of this solution is that we don't need to introduce an extra concept like store.

Really like that idea! I will try to implement this as soon as possible

**Comment by freekmurze** [comment]
Closing this in favour of your next PR :-)

**Pull request closed without merging**
