### PR TITLE
Use default webhook response as fallback

### PR DESCRIPTION
**Pull request by gdebrauwer**
Related to #56

### CODE REVIEW

**Comment by gdebrauwer** [comment]
I have no idea why scrutinizer fails 🤔

**Comment by freekmurze** [comment]
Thanks!

**Comment by gdebrauwer** [comment]
Sorry that I did not mention my initial PR contained a breaking change 😞

**Comment by freekmurze** [comment]
Np, these things can happen. Didn't spot it myself. No worries, appreciate your contribution.

**Pull request merged**
