### PR TITLE
Add config so signing can be completely avoided.

### PR DESCRIPTION
**Pull request by leeovery**
Default is that signature validation will occur unless config 'is_signed' is set to false. Tests added and checked.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work. I don't want a config option for this. Checking if the signature exist should be moved to the signer, so people that want to disable the signing can just return `true` from the signer.

**Comment by leeovery** [comment]
That was my original plan but then thought the config option was cleaner. 

I’ll start again :) and do it the way I originally said lol

Thanks!!

**Comment by leeovery** [comment]
Started again with fresh PR.

**Comment by dreammonkey** [comment]
> Thanks for your work. I don't want a config option for this. Checking if the signature exist should be moved to the signer, so people that want to disable the signing can just return `true` from the signer.

Hello, this is exactly what I'm trying to implement because I'm tasked with setting up a webhook (receiving end) for an existing (unsigned) webhook call.

My Validator Class:
/Acme/PhonySignatureValidator.php
```php
<?php

namespace Acme;

use Illuminate\Http\Request;
use Spatie\WebhookClient\SignatureValidator\SignatureValidator;
use Spatie\WebhookClient\WebhookConfig;

class PhonySignatureValidator implements SignatureValidator
{
    public function isValid(Request $request, WebhookConfig $config): bool
    {
        return true;
    }
}
``` 
config (webhook-client.php):
```php
...
'signature_validator' => \Acme\PhonySignatureValidator::class,
...
```
But when calling the hook, I always get this error: 

`Acme\PhonySignatureValidator` is not a valid signature validator class. A valid signature validator
		is a class that implements `Spatie\WebhookClient\SignatureValidator\SignatureValidator`.

I must be overseeing something... ?

**Pull request closed without merging**
