### PR TITLE
Add a unique token to route names

### LINKED ISSUE #209: Route caching fails when multiple routes use same configuration
### Description
If two or more routes use the same configuration name then route caching fails. According to [this section](https://github.com/spatie/laravel-webhook-client?tab=readme-ov-file#change-route-method) of the README, multiple routes should be acceptable for a single webhook configuration. Looking in `Spatie\WebhookClient\WebhookClientServiceProvider`, it appears that the route macro simply appends the configuration name to magic string. This leads to non-unique names for routes which are a problem when routes are serialized during caching.

### Steps To Reproduce
- Add `Route::webhooks('receiving-url-for-app-1', 'default', 'get')` to your routes file
- Add `Route::webhooks('receiving-url-for-app-1', 'default', 'post')` to your routes file
- Run `php artisan route:cache` or `php artisan optimize` to cache the routes.
- See that a `LogicException` is thrown when serialization is attempted.

### Screenshots
Screenshot 2024-04-22 at 11 43 52 AM
Screenshot 2024-04-22 at 11 43 38 AM

### PR DESCRIPTION
**Pull request by ryanlholt**
Closes #209

### CODE REVIEW

**Comment by it-can** [comment]
This bit me in the *** today... is there a way to disable this?

**Comment by freekmurze** [comment]
@ryanlholt seems like this behaviour can be breaking. Could you introduce a config value to enable this behaviour?

**Comment by it-can** [comment]
this is a problem when using the webhook routes like this:

```
route('webhook-client-mollie')
```

**Comment by ryanlholt** [comment]
@freekmurze I certainly can but it looks like @it-can has an open PR that only needs a slight change to work. Should we default the config value to `true` since the non-tokenized routes were already breaking documented functionality?

**Pull request merged**
